language:
  - node_js
node_js:
   - 14
branches:
  only:
    - main
install:
 #- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
 #- git fetch --tags --depth=10000
 - npm install
 #- npm version patch -m "[ci skip] version bumped %s"
script:
 - npm test
 - npm run build-prod
deploy:
  provider: pages
  local_dir: www
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
env:
  global:
    - GH_REPO: "ofidj/fidj-app"
