language:
  - node_js
node_js:
   - 14
branches:
  only:
    - main
install:
 - npm install
script:
 - npm test
 - npm run build-prod
 - echo "fidj.ovh" > www/CNAME
deploy:
  provider: pages
  local_dir: www
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: false
  on:
    branch: main
env:
  global:
    - GH_REPO: "ofidj/fidj-app"
